tinyMCE.addI18n('nl.xhtmlxtras_dlg',{
attribute_label_title:"Titel",
attribute_label_id:"ID",
attribute_label_class:"Class",
attribute_label_style:"Stijl",
attribute_label_cite:"Citaat",
attribute_label_datetime:"Datum/Tijd",
attribute_label_langdir:"Tekstrichting",
attribute_option_ltr:"Links naar Rechts",
attribute_option_rtl:"Rechts naar links",
attribute_label_langcode:"Taal",
attribute_label_tabindex:"Tabvolgorde",
attribute_label_accesskey:"Toegangstoets",
attribute_events_tab:"Gebeurtenissen",
attribute_attrib_tab:"Objecten",
general_tab:"Algemeen",
attrib_tab:"Objecten",
events_tab:"Gebeurtenissen",
fieldset_general_tab:"Algemene instellingen",
fieldset_attrib_tab:"Element obecten",
fieldset_events_tab:"Element gebeurtenissen",
title_ins_element:"Invoeging",
title_del_element:"Verwijdering",
title_acronym_element:"Letterwoord",
title_abbr_element:"Afkorting",
title_cite_element:"Citaat",
remove:"Verwijderen",
insert_date:"Huidige datum/tijd invoegen",
option_ltr:"Links naar Rechts",
option_rtl:"Rechts naar links",
attribs_title:"Invoegen/bewerken objecten"
});