tinyMCE.addI18n(
'de.dlg',{
// JCE specific
modified: 'Geändert',
file: 'Datei',
folder: 'Verzeichnis',
files: 'Dateien',
folders: 'Verzeichnisse',
comments: 'Kommentare',
size: 'Größe',
preview: 'Vorschau',
duration: 'Dauer',
dimensions: 'Format',
contents: 'Inhalte',
unwritable: 'Nicht beschreibbar',
bad_name: 'Unzulässiger Datei- oder Verzeichnisname',
message_tree: 'Erstelle Baumstruktur...',
message_load: 'lädt ...',
message_properties: 'Empfange Eigenschaften...',
current_dir: 'Das aktuelle Verzeichnis: ',
help: 'Hilfe',
name: 'Name',
'options': 'Optionen',
'confirm': 'Bestätigen',
yes: 'Ja',
no: 'Nein',
'alert': 'Hinweis',
folder_new: 'Neues Verzeichnis',
rename: 'Umbenennen',
'delete': 'Löschen',
save:'Speichern',
delete_item_alert: 'Auswahl löschen?',
rename_folder: 'Verzeichnis umbennen',
rename_file: 'Datei umbennen',
rename_item_alert: 'Dateien / Verzeichnisse umzubenennen wird existierende Verknüpfungen lösen. Trotzdem fortfahren?',
file_select: 'Auf einen Dateinamen klicken um einzufügen, rechts neben den Namen klicken um seine Eigenschaften zu sehen. Strg+Klick wählt mehrere Dateien.',
notwritable: 'Nicht beschreibbar',
notwritable_desc: 'Nicht beschreibbar :: Datei oder Verzeichnis ist nicht beschreibbar und kann nicht umbenannt, verschoben oder gelöscht werden.',
bad_name: 'Unzulässiger Datei- oder Verzeichnisname',
bad_name_desc: 'Unzulässiger Datei- oder Verzeichnisname :: Datei/Verzeichnisnamen dürfen nur folgende Zeichen beinhalten: a-zA-Z0-9_-.',
select_value: 'Wert hinzufügen',
select_label:'Wert hinzufügen',
size_bytes:'Byte',
size_kb:'KB',
size_mb:'MB',
date_format:'',
media_not_supported:'Mediatyp wird nicht unterstützt',
one_of_many:'%o von %m',
element_selection:'Elementauswahl',
uploading: 'lädt hoch...',
upload: 'Hochladen',
queue: 'Warteschlange',
upload_drop:'Datei hier ablegen',
cancel: 'Abbrechen',
ok: 'OK',
browse: 'Durchsuchen',
file_extension_error:'Dateityp nicht unterstützt',
file_size_error:'Dateigröße übersteigt die maximale Uploadgröße',
file_invalid_error:'Ungültiger Dateityp',
upload_queue:'Warteschlange',
close:'Schließen',
add:'Datei +',
clear:'Liste -leer-',
'-600':'%f (%s) überschreitet die maximal erlaubte Größe von %m',
'-601':'File: %s',
'-800':'File: %s'
}
);