tinyMCE.addI18n('fr.dlg',{
// JCE specific
modified: 'Modifier',
file: 'Fichier',
folder: 'Dossier',
files: 'Fichiers',
folders: 'Dossiers',
comments: 'Commentaire',
size: 'Poids',
preview: 'Prévisualiser',
duration: 'Durée',
dimensions: 'Dimensions',
contents: 'Contenus',
unwritable: 'Verrouillé',
bad_name: 'Nom de fichier ou de dossier incorrect',
message_tree: 'Analyse de l\'arborescence...',
message_load: 'Chargement...',
message_properties: 'Recherche des propriétés...',
current_dir: 'Actuellement: ',
help: 'Aide',
name: 'Nom',
'options': 'Options',
'confirm': 'Confirmer',
yes: 'Oui',
no: 'Non',
'alert': 'Attention',
folder_new: 'Nouveau dossier',
rename: 'Renommer',
'delete': 'Supprimer',
save:'Sauver',
delete_folder_alert: 'Supprimer le dossier ?',
delete_file_alert: 'Supprimer le(s) fichier(s) ?',
delete_item_alert: 'Supprimer le(s) fichier(s) ?',
rename_folder: 'Renommer le dossier',
rename_file: 'Renommer le fichier',
rename_item_alert: 'Renommer le fichier/dossier supprimera les liens y conduisant. Voulez-vous continuer ?',
file_select: 'Cliquez sur le nom pour choisir un fichier. CTRL+Clic pour choisir plusieurs fichiers.',
notwritable: 'Ecriture impossible',
notwritable_desc: 'Ecriture impossible::Le dossier ou le fichier ne sont pas en mode Ecriture (CHMOD 767 ou 777). Vous ne pouvez pas le renommer, le déplacer ou le supprimer!',
bad_name: 'Nom de fichier ou de dossier incorrect',
bad_name_desc: 'Nom de fichier ou de dossier incorrect::Les fichiers et les dossiers doivent contenir uniquement les caracteres a-z 0-9 _ - .',
select_value: 'Ajouter',
select_label: 'Ajouter',
size_bytes : 'Octets',
size_kb : 'Ko',
size_mb : 'Mo',
date_format : '',
media_not_supported:'Ce type de média n´est pas supporté dans ce gestionnaire de fichiers',
one_of_many : '%o de %m',
element_selection : 'Sélection de l´élément',
/**
 * Upload
 */
uploading: 'Envoi...',
upload: 'Envoyer',
queue: 'File d´attente',
upload_exists: 'Action si le fichier existe: ',
overwrite: 'Remplacer le fichier',
unique: 'Attribuer un nom unique',
cancel: 'Fermer',
ok: 'Valider',
browse: 'Parcourir...',
'options': 'Options',
'confirm': 'Confirmation',
file_extension_error : 'Ce type de fichier n´est pas supporté',
file_size_error : 'Le poids du fichier dépasse celui autorisé par le serveur.',
file_invalid_error : 'Type de fichier invalide',
add : 'Ajout',
clear : 'Vider',
upload_drop : 'Glisser... &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; les fichiers dans cette fenêtre',
close : 'Fermer',
/**
 * Upload Error Codes
 */
'-600' : 'Fichier: %f, taille: %s, taille max du fichier: %m',
'-601' : 'Fichier: %s',
'-800' : 'Fichier: %s'
});