tinyMCE.addI18n('nl.dlg',{
// JCE specific
modified: 'Bewerkt',
file: 'Bestand',
folder: 'Map',
files: 'bestanden',
folders: 'mappen',
comments: 'Commentaar',
size: 'Grootte',
preview: 'Voorbeeld',
duration: 'Gedurende',
dimensions: 'Dimensies',
contents: 'Inhoud',
unwritable: 'Onschrijfbaar',
bad_name: 'Foute bestands- of mapnaam',
message_tree: 'Lijst opbouwen...',
message_load: 'Laden...',
message_properties: 'Eigenschappen ophalen...',
current_dir: 'Huidige map is: ',
help: 'Help',
name: 'Naam',
'options': 'Opties',
'confirm': 'Bevestig',
yes: 'Ja',
no: 'Nee',
'alert': 'Let op',
folder_new: 'Nieuwe map',
rename: 'Hernoemen',
'delete': 'Verwijderen',
delete_item_alert:'Verwjder geselecteerde item(s)?,
rename_folder: 'Map hernoemen',
rename_file: 'Bestand hernoemen',
rename_item_alert: 'Hernoemen van bestanden/mappen verbreekt bestaande links. Doorgaan?',
file_select: 'Klik op een bestandsnaam om deze in te voegen, rechts klikken om de eigenschappen te bekijken. CTRL+Click selecteert meerdere bestanden.',
notwritable: 'Onschrijfbaar',
notwritable_desc: 'Onschrijfbaar::Map of bestand is niet schrijfbaar en kan niet hernoemd, verplaatst of verwijderd worden.',
bad_name: 'Foute bestands- of mapnaam',
bad_name_desc: 'Foute bestands- of mapnaam::De naam van een map/bestand kan alleen de karakters a-z0-9_- bevatten.',
select_value: 'Waarde toevoegen',
select_label: 'Waarde toevoegen',
size_bytes : 'Bytes',
size_kb : 'KB',
size_mb : 'MB',
date_format : '',
media_not_supported:'Mediatype wordt niet ondersteund door deze browser',
one_of_many : '%o van %m',
element_selection:'Element selectie',
/**
 * Upload
 */
uploading: 'Uploaden...',
upload: 'Upload',
queue: 'Wachtrij',
upload_exists: 'Als bestand bestaat: ',
overwrite: 'Bestaande bestanden overschrijven',
upload_drop: 'Klik & sleep bestanden hier',
file_exists_alert: 'Een bestand met de zelfde naam bestaat al in de doelmap. Hernoem het bestand in de rij of selecteer "Unieke naam geven" in de "Als bestand bestaat" lijst.',
unique: 'Unieke naam geven',
cancel: 'Afbreken',
ok: 'OK',
browse: 'Bladeren',
file_extension_error : 'Bestandstype niet ondersteund',
file_size_error : 'Bestandsgrootte overschreid maximale toegestane grootte',
file_invalid_error : 'Ongeldig bestandstype',
add : 'Bestand toevoegen',
clear : 'Rij wissen',
upload_drop : 'Sleep bestanden hier naartoe',
/**
 * Upload Error Codes
 */
'-600' : '%f (%s) overschreidt de maximumbestandsgrootte %m',
'-601' : 'Bestand: %s',
'-800' : 'Bestand: %s',
/**
* Added by JC
*/
close: 'Sluiten'
});