// Le portail de présentation francophone de JCE: jce.sarki.ch 
// Traductions et supports francophones par Sarki: www.sarki.ch
tinyMCE.addI18n('fr.media_dlg',{
title:"Insérer/Editer un média",
desc:"Insérer/Editer un média",
delta_width: 0,
delta_height: 0,
no_src: 'Veuillez sélectionner le média ou indiquer son URL',
no_width: 'Une valeur de largeur est requise',
no_height: 'Une valeur de hauteur est requise',
is_external: "L'adresse URL indiquée est externe au site. Voulez-vous ajouter le préfixe http:// nécessaire ?",
add_controls_height: "Voulez-vous ajouter une valeur de hauteur pour le contrôleur du média (cette valeur a peut-être déjà été ajoutée si vous êtes en réédition)?"
general:"Général",
advanced:"Avancé",
file:"Fichier/URL",
list:"Liste",
size:"Dimensions",
preview:"Aperçu",
constrain_proportions:"Proportion",
type:"Type",
id:"Id",
name:"Nom",
class_name:"Style",
vspace:"Espace vertical",
hspace:"Espace horizontal",
play:"Démarrage Auto",
loop:"En boucle",
menu:"Afficher menu",
quality:"Qualité",
scale:"Affichage",
align:"Alignement",
salign:"SAlignement",
wmode:"Transparence",
bgcolor:"Fond",
base:"Base",
flashvars:"Variables Flash",
liveconnect:"SW Connection directe",
autohref:"Adresse href Automatique",
cache:"Cache",
hidden:"Masqué",
controller:"Contrôles",
kioskmode:"Mode Kiosk pour IE",
playeveryframe:"Jouer toutes les images",
targetcache:"Cache ciblé",
correction:"Aucune correction",
enablejavascript:"Activer JavaScript",
starttime:"Image de départ",
endtime:"Image de fin",
href:"Adresse href",
qtsrcchokespeed:"Vitesse Choke",
target:"Cible",
volume:"Volume",
autostart:"Démarrage Auto",
enabled:"Activé",
fullscreen:"Pleine page",
invokeurls:"Appeler URLs",
mute:"Muet",
stretchtofit:"Adaptation à la taille",
windowlessvideo:"Vidéo sans cadre",
balance:"Balance",
baseurl:"URL de Base",
captioningid:"Id Légende",
currentmarker:"Marqueur actuel",
currentposition:"Position actuelle",
defaultframe:"Taille par défaut",
playcount:"Jouer chapître",
rate:"Vitesse",
uimode:"UI Mode",
flash_options:"Options Flash",
qt_options:"Options Quicktime",
wmp_options:"Options Windows media player",
rmp_options:"Options Real media player",
shockwave_options:"Options Shockwave",
autogotourl:"Atteindre URL automatiquement",
center:"Centré",
imagestatus:"Statut Image",
maintainaspect:"Proportionnel",
nojava:"Java desactivé",
prefetch:"Activer Prefetch",
shuffle:"Mode aléatoire",
console:"Activer Console",
numloop:"Nombre de boucle",
controls:"Contrôles",
scriptcallbacks:"Script callbacks",
swstretchstyle:"Stretch style",
swstretchhalign:"Stretch H-Alignement",
swstretchvalign:"Stretch V-Alignement",
sound:"Son",
progress:"Progression",
qtsrc:"Source Quicktime",
qt_stream_warn:"Vous devez ajouter le source du Streaming rtsp dans le champ Source Quicktime de l'onglet avancé.\nVous devriez ajouter égalementune la version du Streaming rtsp",
align_top:"Haut",
align_right:"Droite",
align_bottom:"Bas",
align_left:"Gauche",
align_center:"Centré",
align_top_left:"Haut Gauche",
align_top_right:"Haut Droite",
align_bottom_left:"Bas Gauche",
align_bottom_right:"Bas Droite",
flv_options:"Options vidéo Flash",
flv_scalemode:"Mode affichage",
flv_buffer:"Tampon",
flv_startimage:"Image de départ",
flv_starttime:"Point de départ",
flv_defaultvolume:"Volume par défaut",
flv_hiddengui:"Masquer GUI (Graphical User Interface)",
flv_autostart:"Démarrage Auto",
flv_loop:"Boucle",
flv_showscalemodes:"Afficher les modes proportion",
flv_smoothvideo:"Smooth vidéo",
flv_jscallback:"JS Callback"
});