tinyMCE.addI18n('en.imgmanager_ext_dlg',{
missing_alt: "Are you sure you want to continue without including an Image Description? Without it the image may not be accessible to some users with disabilities, or to those using a text browser, or browsing the Web with images turned off.",
delta_width: 0,
delta_height: 0,
'-90': '90&deg; CW',
'90': '90&deg; CCW',
'180': '180&deg;',
'vertical': 'Flip Vertical',
'horizontal': 'Flip Horizontal',
'view_images': 'Thumbnail View',
'view_list': 'List View',
'use_thumbnail': 'Use associated thumbnail?',
'resize': 'Resize',
'rotate': 'Rotate',
'proportional': 'Proportional',
'cropped': 'Cropped',
'mode': 'Mode',
'quality': 'Quality',
'size': 'Size',
'thumbnail': 'Thumbnail',
'transform': 'Transform',
'width': 'Width',
'height': 'Height',
'create_thumbnail': 'Create Thumbnail',
'delete_thumbnail': 'Delete Thumbnail?',
'required_jcemediabox': 'Requires JCE MediaBox Plugin',
'required_script': 'Requires 3rd party frontend script',
'required_window': 'Requires JCE Administration Component',
'message_images': 'Click on an image to view its properties, double-click to insert it. CTRL+Click selects multiple images.',
'message_list': 'Click on an image name to insert, click to the right of the name to view its properties. CTRL+Click selects multiple images.',
no_src: 'Please select an image or enter an image URL.'
});