// Le portail de présentation francophone de JCE: jce.sarki.ch 
// Traductions et supports francophones par Sarki: www.sarki.ch
tinyMCE.addI18n('fr.imgmanager_ext_dlg',{
missing_alt: "Êtes-vous sûr de vouloir insérer une image sans inclure de description? Sans elle, l'image sera invisible pour les sytèmes de lecture (malvoyants, etc.), pour les navigateurs dont l'affichage des images est désactivé et, pour les moteurs de recherche!",
delta_width: 0,
delta_height: 0,
'-90': '90o; Droite',
'90': '90o; Gauche',
'180': '180o;',
'vertical': 'Rotation Verticale',
'horizontal': 'Rotation Horizontale',
'view_images': 'Visualisation Mignatures',
'view_list': 'Visualisation Liste',
'switch mode': 'Changer de visualisation',
'use_thumbnail': 'Utiliser la mignature associée?',
'resize': 'Redimensionner',
'rotate': 'Rotation',
'proportional': 'Proportionnel',
'cropped': 'Carré',
'mode': 'Mode',
'quality': 'Qualité',
'size': 'Taille',
'thumbnail': 'Mignature',
'transform': 'Modifier',
'width': 'Largeur',
'height': 'Hauteur',
'create_thumbnail': 'Créer une mignature',
'delete_thumbnail': 'Effacer la mignature',
'required_jceutilities': 'Requiert le Plugin JCE MediaBox ',
'required_script': 'Requiert le script correspondant',
'required_window': 'Requiert le composant JCE',
'message_images': 'Cliquer sur une image pour voir ses propriétés et l\'insérer. CTRL+Clic pour séléctionner plusieurs images',
'message_list': 'Cliquer sur le nom de l\'image pour voir ses propriétés et l\'insérer. CTRL+Clic pour séléctionner plusieurs images',
'imgmanager_ext_dlg.required_script': 'Cette fonction requiert le script',
no_src: 'Une URL est equise. Veuillez choisir une image ou entrer un adresse URL'
});