tinyMCE.addI18n('de.dlg',{
// JCE specific
modified: 'Geändert',
file: 'Datei',
folder: 'Verzeichnis',
files: 'Dateien',
folders: 'Verzeichnisse',
comments: 'Kommentare',
size: 'Größe',
preview: 'Vorschau',
duration: 'Dauer',
dimensions: 'Format',
contents: 'Inhalte',
unwritable: 'Nicht beschreibbar',
bad_name: 'Unzulässiger Datei- oder Verzeichnisname',
message_tree: 'Erstelle Baumstruktur...',
message_load: 'lädt ...',
message_properties: 'Empfange Eigenschaften...',
current_dir: 'Das aktuelle Verzeichnis: ',
help: 'Hilfe',
name: 'Name',
uploading: 'lädt hoch...',
upload: 'Upload',
queue: 'Warteschlange',
upload_exits: 'Aktion falls Datei bereits vorhanden: ',
overwrite: 'Datei überschreiben',
unique: 'Eindeutigen Namen erzeugen',
cancel: 'Abbrechen',
ok: 'OK',
browse: 'Durchsuchen',
'options': 'Optionen',
'confirm': 'Bestätigen',
yes: 'Ja',
no: 'Nein',
'alert': 'Hinweis',
new_folder: 'Neues Verzeichnis',
rename: 'Umbenennen',
'delete': 'Löschen',
delete_folder_alert: 'Verzeichnis löschen?',
delete_file_alert: 'Datei(en) löschen?',
rename_folder: 'Verzeichnis umbennen',
rename_file: 'Datei umbennen',
rename_alert: 'Dateien / Verzeichnisse umzubenennen wird existierende Verknüpfungen lösen. Trotzdem fortfahren?',
file_select: 'Auf einen Dateinamen klicken um einzufügen, rechts neben den Namen klicken um seine Eigenschaften zu sehen. Strg+Klick wählt mehrere Dateien.',
notwritable: 'Nicht beschreibbar',
notwritable_desc: 'Nicht beschreibbar :: Datei oder Verzeichnis ist nicht beschreibbar und kann nicht umbenannt, verschoben oder gelöscht werden.',
bad_name: 'Unzulässiger Datei- oder Verzeichnisname',
bad_name_desc: 'Unzulässiger Datei- oder Verzeichnisname :: Datei/Verzeichnisnamen dürfen nur folgende Zeichen beinhalten: a-zA-Z0-9_-.',
select_value: 'Wert hinzufügen'
});