tinyMCE.addI18n('nl.dlg',{
// JCE specific
modified: 'Bewerkt',
file: 'Bestand',
folder: 'Map',
files: 'bestanden',
folders: 'mappen',
comments: 'Commentaar',
size: 'Grootte',
preview: 'Voorbeeld',
duration: 'Gedurende',
dimensions: 'Dimensies',
contents: 'Inhoud',
unwritable: 'Onschrijfbaar',
bad_name: 'Foute bestands- of mapnaam',
message_tree: 'Lijst opbouwen...',
message_load: 'Laden...',
message_properties: 'Eigenschappen ophalen...',
current_dir: 'Huidige map is: ',
help: 'Help',
name: 'Naam',
uploading: 'Uploaden...',
upload: 'Upload',
queue: 'Wachtrij',
upload_exists: 'Actie als bestand bestaat: ',
overwrite: 'Bestand overschrijven',
unique: 'Unieke naam geven',
cancel: 'Afbreken',
ok: 'OK',
browse: 'Bladeren',
'options': 'Opties',
'confirm': 'Bevestig',
yes: 'Ja',
no: 'Nee',
'alert': 'Let op',
folder_new: 'Nieuwe map',
rename: 'Hernoemen',
'delete': 'Verwijder',
delete_folder_alert: 'Verwijder map?',
delete_file_alert: 'Verwijder bestand(en)?',
rename_folder: 'Map hernoemen',
rename_file: 'Bestand hernoemen',
rename_alert: 'Hernoemen van bestanden/mappen verbreekt bestaande links. Doorgaan?',
file_select: 'Klik op een bestandsnaam om deze in te voegen, rechts klikken om de eigenschappen te bekijken. CTRL+Click selecteert meerdere bestanden.',
notwritable: 'Onschrijfbaar',
notwritable_desc: 'Onschrijfbaar::Map of bestand is niet schrijfbaar en kan niet hernoemd, verplaatst of verwijderd worden.',
bad_name: 'Foute bestands- of mapnaam',
bad_name_desc: 'Foute bestands- of mapnaam::De naam van een map/bestand kan alleen de karakters a-z0-9_- bevatten.',
select_value: 'Waarde toevoegen',
add: 'Voeg toe',
clear: 'Wissen',
close: 'Sluiten'
});