tinyMCE.addI18n('nl.emotions_dlg',{
title:"Emoticon invoegen",
desc:"Emoticons",
cool:"Stoer",
cry:"Huilen",
embarassed:"Beschaamd",
foot_in_mouth:"Mond snoeren",
frown:"Fronsen",
innocent:"Onschuldig",
kiss:"Zoenen",
laughing:"Lachen",
money_mouth:"Inhalig",
sealed:"Gesloten",
smile:"Glimlach",
surprised:"Verrast",
tongue_out:"Tong uitsteken",
undecided:"Onbeslist",
wink:"Knipogen",
yell:"Roepen"
});