tinyMCE.addI18n('fr.advanced_dlg',{
about_title:"Présentation TinyMCE",
about_general:"Présentation",
about_help:"Aide",
about_license:"License",
about_plugins:"Plugins",
about_plugin:"Plugin",
about_author:"Auteur",
about_version:"Version",
about_loaded:"Charger des plugins",
anchor_title:"Insérer/Modifier une ancre",
anchor_name:"Nom de l'ancre",
anchor_invalid:"Veuillez spécifier un nom d'ancre ou une ID valide ; un nom doit commencer par une lettre",
code_title:"Editeur de code HTML",
code_wordwrap:"Retour automatique à la ligne",
colorpicker_title:"Choisissez une couleur...",
colorpicker_picker_tab:"Pipette",
colorpicker_picker_title:"Toutes les couleurs",
colorpicker_palette_tab:"Web",
colorpicker_palette_title:"Couleurs Web",
colorpicker_named_tab:"Nommée",
colorpicker_template_tab:"Template",
colorpicker_named_title:"Couleurs Nommées",
colorpicker_template_title:"Couleurs du Template (habillage) du site",
colorpicker_color:"Couleur:",
colorpicker_name:"Nom:",
charmap_title:"Caractères spéciaux",
image_title:"Insérer/Modifier une image",
image_src:"URL de l'image",
image_alt:"Description",
image_list:"Liste Image",
image_border:"Bordure",
image_dimensions:"Dimensions",
image_vspace:"Espace vertical",
image_hspace:"Espace horizontal",
image_align:"Alignement",
image_align_baseline:"Ligne de base",
image_align_top:"Haut",
image_align_middle:"Milieu",
image_align_bottom:"Bas",
image_align_texttop:"Haut du texte",
image_align_textbottom:"Bas du texte",
image_align_left:"Gauche",
image_align_right:"Droite",
link_title:"Insérer/Modifier un lien",
link_url:"URL",
link_target:"Cible",
link_target_same:"Ouvrir dans la même fenêtre",
link_target_blank:"Ouvrir dans une nouvelle fenêtre",
link_titlefield:"Titre",
link_is_email:"L'URL semble être une adresse email. Voule-vous ajouter le préfixe mailto: exigé?",
link_is_external:"L'URL semble être une adresse externe au site. Voule-vous ajouter le préfixe http:// exigé?",
link_list:"Liste Liens",
accessibility_help:"Aide à l'accessibilité",
accessibility_usage_title:"Usage général"
});