tinyMCE.addI18n('de.xhtmlxtras_dlg',{
attribute_label_title:'Titel',
attribute_label_id:'ID',
attribute_label_class:'Klasse',
attribute_label_style:'Style',
attribute_label_cite:'Zitat',
attribute_label_datetime:'Datum/Zeit',
attribute_label_langdir:'Schriftrichtung',
attribute_option_ltr:'Links nach Rechts',
attribute_option_rtl:'Rechts nach Links',
attribute_label_langcode:'Sprachcode',
attribute_label_tabindex:'Tabulatorenindex',
attribute_label_accesskey:'Zugriffstaste',
attribute_events_tab:'Ereignisse',
attribute_attrib_tab:'Attribute',
general_tab:'Allgemein',
attrib_tab:'Attribute',
events_tab:'Ereignisse',
fieldset_general_tab:'Allgemeine Einstellungen',
fieldset_attrib_tab:'Element-Attribute',
fieldset_events_tab:'Element-Ereignisse',
title_ins_element:'Einfügemarkierung',
title_del_element:'Entfernemarkierung',
title_acronym_element:'Abkürzung',
title_abbr_element:'Kurzwort',
title_cite_element:'Zitat',
remove:'Löschen',
insert_date:'Aktuelle Zeit/Datum einfügen',
option_ltr:'Links nach Rechts',
option_rtl:'Rechts nach Links',
attribs_title:'Attribute einfügen/bearbeiten'
});
