// Le portail de présentation francophone de JCE: jce.sarki.ch 
// Traductions et supports francophones par Sarki: www.sarki.ch
tinyMCE.addI18n('fr.xhtmlxtras_dlg',{
attribute_label_title:"Titre",
attribute_label_id:"ID unique",
attribute_label_class:"Classes CSS",
attribute_label_style:"Styles",
attribute_label_cite:"Citation",
attribute_label_datetime:"Date/Heure",
attribute_label_langdir:"Direction du Texte",
attribute_option_ltr:"Gauche à droite",
attribute_option_rtl:"Droite à gauche",
attribute_label_langcode:"Code Langue",
attribute_label_tabindex:"Index Table",
attribute_label_accesskey:"Combinaison clavier",
attribute_events_tab:"Evènements",
attribute_attrib_tab:"Attributs",
general_tab:"Général",
attrib_tab:"Attributs",
events_tab:"Evènements",
fieldset_general_tab:"Informations",
fieldset_attrib_tab:"Attributs",
fieldset_events_tab:"Evènement",
title_ins_element:"Elément Souligné",
title_del_element:"Elément Barré",
title_acronym_element:"Elément Acronyme",
title_abbr_element:"Elément Abréviation",
title_cite_element:"Elément Citation",
remove:"Supprimer",
insert_date:"Insérer la date/heure courante",
option_ltr:"Gauche à droite",
option_rtl:"Droite à gauche",
attribs_title:"Insérer/Editer Evènement"
});