// Le portail de présentation francophone de JCE: jce.sarki.ch 
// Traductions et supports francophones par Sarki: www.sarki.ch
tinyMCE.addI18n('fr.dlg',{
// JCE specific
modified: 'Modifier',
file: 'Fichier',
folder: 'Dossier',
files: 'Fichiers',
folders: 'Dossiers',
comments: 'Commentaire',
size: 'Poids',
preview: 'Prévisualiser',
duration: 'Durée',
dimensions: 'Dimensions',
contents: 'Contenus',
unwritable: 'Verrouillé',
bad_name: 'Nom de fichier ou de dossier incorrect',
message_tree: 'Analyse de l\'arborescence...',
message_load: 'Chargement...',
message_properties: 'Recherche des propriétés...',
current_dir: 'Actuellement: ',
help: 'Aide',
name: 'Nom',
uploading: 'Envoi...',
upload: 'Envoyer',
queue: 'File d\'attente',
upload_exists: 'Action si le fichier existe: ',
overwrite: 'Remplacer le fichier',
unique: 'Attribuer un nom unique',
cancel: 'Fermer',
ok: 'Valider',
browse: 'Rechercher sur l\'ordinateur',
'options': 'Options',
'confirm': 'Confirmation',
yes: 'Oui',
no: 'Non',
'alert': 'Attention',
new_folder: 'Nouveau dossier',
rename: 'Renommer',
'delete': 'Effacer',
delete_folder_alert: 'Supprimer le dossier ?',
delete_file_alert: 'Effacer le(s) fichier(s) ?',
rename_folder: 'Renommer le dossier',
rename_file: 'Renommer le fichier',
rename_alert: 'Renommer le fichier/dossier supprimera les liens y conduisant. Voulez-vous continuer ?',
file_select: 'Cliquez sur le nom pour choisir un fichier. CTRL+Clic pour choisir plusieurs fichiers.',
notwritable: 'Ecriture impossible',
notwritable_desc: 'Ecriture impossible::Le dossier ou le fichier ne sont pas en mode Ecriture (CHMOD 767 ou 777). Vous ne pouvez pas le renommer, le déplacer ou le supprimer!',
bad_name: 'Nom de fichier ou de dossier incorrect',
bad_name_desc: 'Nom de fichier ou de dossier incorrect::Les fichiers et les dossiers doivent contenir uniquement les caracteres a-z 0-9 _ - .',
select_value: 'Ajouter'
});