// Le portail de présentation francophone de JCE: jce.sarki.ch 
// Traductions et supports francophones par Sarki: www.sarki.ch
tinyMCE.addI18n('fr.style_dlg',{
title:"Insérer/Editer des styles XHTML dans la balise",
apply:"Appliquer",
text_tab:"Texte",
background_tab:"Fond",
block_tab:"Bloc",
box_tab:"Boîte",
border_tab:"Bordure",
list_tab:"Liste",
positioning_tab:"Position",
text_props:"Texte",
text_font:"Police",
text_size:"Taille",
text_weight:"Largeur",
text_style:"Style",
text_variant:"Variante",
text_lineheight:"Hauteur de ligne",
text_case:"Case",
text_color:"Couleur",
text_decoration:"Décoration",
text_overline:"Ligne au dessus",
text_underline:"Souligné",
text_striketrough:"Barré",
text_blink:"Clignotement",
text_none:"Aucun",
background_color:"Couleur de fond",
background_image:"Image de fond",
background_repeat:"Répéter",
background_attachment:"Lier",
background_hpos:"Position horizontale",
background_vpos:"Position verticale",
block_wordspacing:"Espacement des mots",
block_letterspacing:"Espacement des lettres",
block_vertical_alignment:"Alignement vertical",
block_text_align:"Alignement du texte",
block_text_indent:"Retrait du texte",
block_whitespace:"Espace blanc",
block_display:"Affichage",
box_width:"Largeur",
box_height:"Hauteur",
box_float:"Position",
box_clear:"Eléments externes",
padding:"Marge intérieure",
same:"Identique",
top:"Haut",
right:"Droite",
bottom:"Bas",
left:"Gauche",
margin:"Marge extérieure",
style:"Style",
width:"Largeur",
height:"Hauteur",
color:"Couleur",
list_type:"Type",
bullet_image:"Puces Image",
position:"Position",
positioning_type:"Type",
visibility:"Visibilité",
zindex:"Z-index",
overflow:"Superposer",
placement:"Positionnement",
clip:"Attachement"
});