tinyMCE.addI18n('nl.style_dlg',{
title:"CSS Stijl bewerken",
apply:"Toepassen",
text_tab:"Tekst",
background_tab:"Achtergrond",
block_tab:"Blok",
box_tab:"Box",
border_tab:"Rand",
list_tab:"Lijst",
positioning_tab:"Positionering",
text_props:"Tekst",
text_font:"Lettertype",
text_size:"Grootte",
text_weight:"Dikte",
text_style:"Stijl",
text_variant:"Variant",
text_lineheight:"Lijnhoogte",
text_case:"Hoofdletter",
text_color:"Kleur",
text_decoration:"Decoratie",
text_overline:"Overhalen",
text_underline:"Onderstrepen",
text_striketrough:"Doorhalen",
text_blink:"Knipperen",
text_none:"Niets",
background_color:"Achtergrondkleur",
background_image:"Achtergrondafbeelding",
background_repeat:"Herhalen",
background_attachment:"Bijlage",
background_hpos:"Horizontale positie",
background_vpos:"Verticale positie",
block_wordspacing:"Tussenruimte woorden",
block_letterspacing:"Tussenruimte letters",
block_vertical_alignment:"Verticale uitlijning",
block_text_align:"Tekstuitlijning",
block_text_indent:"Tekst inspringen",
block_whitespace:"Witruimte",
block_display:"Weergave",
box_width:"Breedte",
box_height:"Hoogte",
box_float:"Zwevend",
box_clear:"Leegmaken",
padding:"Vulling",
same:"Alles hetzelfde",
top:"Boven",
right:"Rechts",
bottom:"Onder",
left:"Links",
margin:"Marge",
style:"Stijl",
width:"Breedte",
height:"Hoogte",
color:"Kleur",
list_type:"Type",
bullet_image:"Opsommingsteken",
position:"Positie",
positioning_type:"Type",
visibility:"Zichtbaarheid",
zindex:"Z-index",
overflow:"Groter dan ",
placement:"Plaatsing",
clip:"Clip"
});