tinyMCE.addI18n('de.advanced_dlg',{
about_title:"Über TinyMCE",
about_general:"Über",
about_help:"Hilfe",
about_license:"Lizenz",
about_plugins:"Plugins",
about_plugin:"Plugin",
about_author:"Autor",
about_version:"Version",
about_loaded:"Geladene plugins",
anchor_title:"Anker einfügen / bearbeiten",
anchor_name:"Ankername",
code_title:"HTML Quelltexteditor",
code_wordwrap:"Zeilenumbruch",
colorpicker_title:"Farbe auswählen",
colorpicker_picker_tab:"Farbwähler",
colorpicker_picker_title:"Farbwähler",
colorpicker_palette_tab:"Palette",
colorpicker_palette_title:"Palettenfarben",
colorpicker_named_tab:"Benannte",
colorpicker_template_tab:"Template",
colorpicker_named_title:"Benannte Farben",
colorpicker_template_title:"Farben des Templates",
colorpicker_color:"Farbe:",
colorpicker_name:"Name:",
charmap_title:"Sonderzeichen wählen",
image_title:"Bild einfügen / bearbeiten",
image_src:"Bilder-URL",
image_alt:"Bildbeschreibung",
image_list:"Bilderliste",
image_border:"Rahmen",
image_dimensions:"Format",
image_vspace:"Vertikaler Abstand",
image_hspace:"Horizontaler Abstand",
image_align:"Ausrichtung",
image_align_baseline:"Grundlinie",
image_align_top:"Obenbündig",
image_align_middle:"Mittig",
image_align_bottom:"Untenbündig",
image_align_texttop:"Oberhalb des Textes",
image_align_textbottom:"Unterhalb des Textes",
image_align_left:"Linksbündig",
image_align_right:"Rechtsbündig",
link_title:"Link einfügen / bearbeiten",
link_url:"Link-URL",
link_target:"Ziel",
link_target_same:"Im selben Fenster öffnen",
link_target_blank:"Im neuen Fenster öffnen",
link_titlefield:"Titel",
link_is_email:"Die URL, welche eingegeben wurde, scheint eine E-Mail Adresse zu sein. Soll der benötigte mailto: Präfix eingefügt werden?",
link_is_external:"Die URL, welche eingegeben wurde, scheint ein externer Link zu sein. Soll der benötigte http:// Präfix eingefügt werden?",
link_list:"Linkliste"
});
