tinyMCE.addI18n('fr.advanced',{
style_select:"Styles CSS",
font_size:"Tailles",
fontdefault:"Polices",
block:"Formats",
paragraph:"Paragraphe",
div:"Div",
address:"Addresse",
pre:"Préformaté",
h1:"Titre 1",
h2:"Titre 2",
h3:"Titre 3",
h4:"Titre 4",
h5:"Titre 5",
h6:"Titre 6",
blockquote:"Retrait",
code:"Code",
samp:"Exemple Code",
dt:"Définition",
dd:"Citation",
bold_desc:"Gras (Ctrl+B)",
italic_desc:"Italique (Ctrl+I)",
underline_desc:"Souligné (Ctrl+U)",
striketrough_desc:"Barré",
justifyleft_desc:"Aligné à gauche",
justifycenter_desc:"Centré",
justifyright_desc:"Aligné à droite",
justifyfull_desc:"Justifié",
bullist_desc:"Liste à puce",
numlist_desc:"Liste numérotée",
outdent_desc:"Diminuer le retrait",
indent_desc:"Augmenter le retrait",
undo_desc:"Annuler (Ctrl+Z)",
redo_desc:"Rétablir (Ctrl+Y)",
link_desc:"Créer un lien",
unlink_desc:"Supprimer le lien",
image_desc:"Insérer/Editer une image",
cleanup_desc:"Nettoyer/Fermer les balises",
code_desc:"Editer le code HTML",
sub_desc:"Indice",
sup_desc:"Exposant",
hr_desc:"Insérer une ligne horizontale",
removeformat_desc:"Supprimer tous les styles",
custom1_desc:"Votre description personnelle",
forecolor_desc:"Appliquer une couleur au texte",
backcolor_desc:"Appliquer une couleur de fond au texte",
charmap_desc:"Insérer un caractère spécial",
visualaid_desc:"Afficher les cadres-lignes des tableaux",
anchor_desc:"Insérer/Editer une ancre",
cut_desc:"Couper",
copy_desc:"Copier",
paste_desc:"Coller",
image_props_desc:"Propriété de l'image",
newdocument_desc:"Effacer le contenu de l'éditeur",
help_desc:"Aide",
blockquote_desc:"Retrait",
clipboard_msg:"La fonction Copier/Coller n'est pas activée sous Mozilla et Firefox. En savoir plus ?",
path:"Chemin",
newdocument:"Voulez-vous effacer tout le contenu de l'éditeur?",
toolbar_focus:"Barre d'outils - Alt+Q, Editeur contenu - Alt-Z, Elément suivant - Alt-X",
more_colors:"Plus de couleurs..."
});