tinyMCE.addI18n('nl.imgmanager_ext_dlg',{
missing_alt: "Weet u zeker dat u door wilt gaan zonder een beschrijving voor de afbeelding in te voegen? Zonder beschrijving is de afbeelding mogelijk niet toegankelijk voor sommige gebruikers met een handicap, of voor mensen die een tekstbrowser gebruiken waarin afbeeldingen uitgeschakeld zijn.",
delta_width: 0,
delta_height: 0,
'-90': '90&deg; CW',
'90': '90&deg; CCW',
'180': '180&deg;',
'vertical': 'Verticaal omdraaien',
'horizontal': 'Horizontaal omdraaien',
'view_images': 'Miniatuurweergave',
'view_list': 'Lijstweergave',
'use_thumbnail': 'Gebruik verbonden miniatuur?',
'resize': 'Formaat aanpassen',
'rotate': 'Roteren',
'proportional': 'Proportioneel',
'cropped': 'Bijsnijden',
'mode': 'Modus',
'quality': 'Kwaliteit',
'size': 'Grootte',
'thumbnail': 'Miniatuur',
'transform': 'Transformeren',
'width': 'Breedte',
'height': 'Hoogte',
'create_thumbnail': 'Miniatuur aanmaken',
'delete_thumbnail': 'Miniatuur verwijderen?',
'required_jceutilities': 'Vereist JCE Utilities Plugin',
'required_script': 'Vereist 3e-partij frontendscript',
'required_window': 'Vereist JCE Administration Component',
'message_images': 'Klik op een afbeelding om de eigenschappen te bekijken, dubbelklik om in te voegen. Selecteer meerdere afbeeldingen met CTRL+Klik.',
'message_list': 'Klik op een afbeeldingsnaam om in te voegen, Klik rechts van de naam om de eigenschappen te bekijken. Selecteer meerdere afbeeldingen met CTRL+Klik.',
no_src: 'Selecteer een afbeelding of vul een URL naar de afbeelding in.'
});