tinyMCE.addI18n('de.table_dlg',{
general_tab:'Allgemein',
advanced_tab:'Erweitert',
general_props:'Allgemeine Eigenschaften',
advanced_props:'Erweiterte Eigenschaften',
rowtype:'Zeile im Tabellenteil',
title:'Tabelle einfügen/bearbeiten',
width:'Breite',
height:'Höhe',
cols:'Spalten',
rows:'Zeilen',
cellspacing:'Außenabst.',
cellpadding:'Innenabst.',
border:'Rahmen',
align:'Ausrichtung',
align_default:'- Standard -',
align_left:'Linksbündig',
align_right:'Rechtsbündig',
align_middle:'Mittig',
row_title:'Zeileneigenschaften',
cell_title:'Zelleneigenschaften',
cell_type:'Zellentyp',
valign:'Vertikale Ausrichtung',
align_top:'Obenbündig',
align_bottom:'Untenbündig',
bordercolor:'Rahmenfarbe',
bgcolor:'Hintergrundfarbe',
merge_cells_title:'Zellen verbinden',
id:'ID',
style:'Stil',
langdir:'Sprachrichtung',
langcode:'Sprachcode',
mime:'Ziel MIME-Typ',
ltr:'Links nach Rechts',
rtl:'Rechts nach Links',
bgimage:'Hintergrundbild',
summary:'Zusammenfassung',
td:'Zelle',
th:'Kopfzelle',
cell_cell:'Aktuelle Zelle aktualisieren',
cell_row:'Alle Zellen in dieser Zeile aktualisieren',
cell_col:'Alle Zellen in dieser Spalte aktualisieren',
cell_all:'Alle Zellen der Tabelle aktualisieren',
row_row:'Diese Zeile aktualisieren',
row_odd:'Ungerade Zeilen aktualisieren',
row_even:'Gerade Zeilen aktualisieren',
row_all:'Alle Zeilen der Tabelle aktualisieren',
thead:'Tabellenkopf',
tbody:'Tabellenkörper',
tfoot:'Tabellenfuß',
scope:'Bereich',
rowgroup:'Zeilengruppe',
colgroup:'Spaltengruppe',
col_limit:'Die maximale Anzahl an Spalten ({$cols}) wurde erreicht.',
row_limit:'Die maximale Anzahl an Zeilen ({$rows}) wurde erreicht.',
cell_limit:'Die maximale Anzahl an Zellen ({$cells}) wurde erreicht.',
missing_scope:'Soll wirklich ohne ein festgelegter Bereich für diese Tabellenkopfzelle fortgefahren werden? Ohne diesen könnte es für manche Benutzer mit Behinderungen schwer sein, den Inhalt der Tabelle zu verstehen.',
caption:'Beschreibung',
frame:'Aufteilung',
frame_none:'Keine',
frame_groups:'Gruppen',
frame_rows:'Zeilen',
frame_cols:'Spalten',
frame_all:'Alle',
rules:'Gitterlinien',
rules_void:'Keine',
rules_above:'Oberhalb',
rules_below:'Unterhalb',
rules_hsides:'Horizontale Seiten',
rules_lhs:'Links',
rules_rhs:'Rechts',
rules_vsides:'Vertikale Seiten',
rules_box:'Rechteck',
rules_border:'Gitter-Rahmen'
});
