tinyMCE.addI18n('fr.table_dlg',{
general_tab:"Général",
advanced_tab:"Avancé",
general_props:"Propriétés générales",
advanced_props:"Propriétés avancées",
rowtype:"Ligne du tableau",
title:"Insérer/Modifer un tableau",
width:"Largeur",
height:"Hauteur",
cols:"Colonnes",
rows:"Lignes",
cellspacing:"Marge extérieure",
cellpadding:"Marge intérieure",
border:"Bordure",
align:"Alignement Horizontal",
align_default:"Défaut",
align_left:"Gauche",
align_right:"Droite",
align_middle:"Centré",
row_title:"Propriétés de la ligne",
cell_title:"Propriétés de la cellule",
cell_type:"Type",
valign:"Alignement vertical",
align_top:"Haut",
align_bottom:"Bas",
bordercolor:"Couleur de bordure",
bgcolor:"Couleur de fond",
merge_cells_title:"Fusionner les cellules",
id:"ID unique",
style:"Styles",
langdir:"Direction d'écriture",
langcode:"Code de langue",
mime:"Target MIME type",
ltr:"Gauche à droite",
rtl:"Droite à gauche",
bgimage:"Image de fond",
summary:"Sommaire",
td:"Données",
th:"En-tête",
cell_cell:"Modifier la cellule active",
cell_row:"Modifier toutes les cellules de la ligne",
cell_all:"Modifier toutes les cellules du tableau",
row_row:"Modifier la ligne active",
row_odd:"Modifier toutes les lignes impaires",
row_even:"Modifier toutes les lignes paires",
row_all:"Modifier toutes les lignes du tableau",
thead:"En-tête",
tbody:"Contenu",
tfoot:"Pied",
scope:"Affecter",
rowgroup:"Lignes",
colgroup:"Colonnes",
col_limit:"Vous avez dépassé le nombre maximum des colonnes de {$cols}.",
row_limit:"Vous avez dépassé le nombre maximum des lignes de {$rows}.",
cell_limit:"Vous avez dépassé le nombre maximum des cellules de {$cells}.",
missing_scope:"Etes vous sûr de ne pas vouloir affecté d'indication à la cellule d'en-tête du tableau? Cette fonction permet aux systèmes de lecture (malvoyants, robots) de mieux décoder le contenu du tableau.",
caption:"Légende",
frame:"Séparation",
frame_none:"Aucun",
frame_groups:"Groupes",
frame_rows:"Lignes",
frame_cols:"Colonnes",
frame_all:"Tous",
rules:"Cadres",
rules_void:"Intérieur",
rules_above:"Intérieur + Lignes dessus",
rules_below:"Colonnes et Lignes",
rules_hsides:"Intérieur + Bord haut",
rules_lhs:"Intérieur + Bord gauche",
rules_rhs:"Intérieur + Bord droite",
rules_vsides:"Intérieur + Bord bas",
rules_box:"Intérieur +  Boîte",
rules_border:"Intérieur + Bords"
});