tinyMCE.addI18n('nl.table_dlg',{
general_tab:"Algemeen",
advanced_tab:"Geavanceerd",
general_props:"Algemene eigenschappen",
advanced_props:"Geavanceerde eigenschappen",
rowtype:"Rijin tabeldeel",
title:"Invoegen/bewerken tabel",
width:"Breedte",
height:"Hoogte",
cols:"Kolommen",
rows:"Rijen",
cellspacing:"Ruimte tussen cellen",
cellpadding:"Celvulling",
border:"Rand",
align:"Uitlijning",
align_default:"Standaard",
align_left:"Links",
align_right:"Rechts",
align_middle:"Centreren",
row_title:"Rij-eigenschappen",
cell_title:"Celeigenschappen",
cell_type:"Celtype",
valign:"Verticale uitlijning",
align_top:"Boven",
align_bottom:"Onder",
bordercolor:"Randkleur",
bgcolor:"Achtergrondkleur",
merge_cells_title:"Cellen samenvoegen",
id:"Id",
style:"Stijl",
langdir:"Taalrichting",
langcode:"Taalcode",
mime:"Doel MIME type",
ltr:"Links naar rechts",
rtl:"Rechts naar links",
bgimage:"Achtergrondafbeelding",
summary:"Samenvatting",
td:"Gegevens",
th:"Kop",
cell_cell:"Huidige cel bijwerken",
cell_row:"Alle cellen in de rij bijwerken",
cell_all:"Alle cellen in de tabel bijwerken",
row_row:"Huidige rij bijwerken",
row_odd:"Oneven rijen in de tabel bijwerken",
row_even:"Even rijen in de tabel bijwerken",
row_all:"Alle rijen in de tabel bijwerken",
thead:"Tabelkop",
tbody:"Tabel midden",
tfoot:"Tabelvoet",
scope:"Bereik",
rowgroup:"Rijgroep",
colgroup:"Kolomgroep",
col_limit:"U heeft het maximale aantal kolommen van {$cols} overschreden.",
row_limit:"U heeft hebt het maximale aantal rijen van {$rows} overschreden.",
cell_limit:"U heeft het maximale aantal cellen van {$cells} overschreden.",
missing_scope:"Weet u zeker dat u wilt doorgaan zonder een bereik op te geven voor de categoriecel van de tabel. Voor mensen met een beperking wordt het misschien moeilijker de ingoud of gegevens in de tabel te begrijpen.",
caption:"Tabelbeschrijving",
frame:"Frame",
frame_none:"Niets",
frame_groups:"Groepen",
frame_rows:"Rijen",
frame_cols:"Kolommen",
frame_all:"Alles",
rules:"Lijnen",
rules_void:"Zonder",
rules_above:"Boven",
rules_below:"Onder",
rules_hsides:"Horizontale zijden",
rules_lhs:"Linkerkant",
rules_rhs:"Rechterkant",
rules_vsides:"Verticale zijden",
rules_box:"Box",
rules_border:"Rand"
});